### PR TITLE
Acquire wakelock in projector mode

### PR DESCRIPTION
**Pull request by hannesfant**
I don't have an environment setup locally where I can try this myself, so please feel free to try and open the projector view before merging to make sure it doesn't crash :)

### CODE REVIEW

**Comment by ttsirkia** [comment]
Thanks, I'll try what happens!

**Comment by ttsirkia** [comment]
Sorry, I haven't had time yet to try this out but is in my todo list!

**Comment by hannesfant** [comment]
> Sorry, I haven't had time yet to try this out but is in my todo list!

No worries, take your time :)

**Comment by ttsirkia** [comment]
I made some improvements for this. It should now work. Sorry for the long delay! I'll ask my ex-colleagues in Aalto if they could update the version in use.

**Pull request merged**
